### ISSUE TITLE
Error on saving module

### ISSUE THREAD

**Issue by operatorone** [1up-lab/contao-sibling-navigation#11] opened 2018-10-27 10:33 UTC
![screenshot 2018-10-27 um 12 30 27](https://user-images.githubusercontent.com/4036452/47602826-2f0dbb00-d9e4-11e8-88a9-c66b11b8be3d.png)

After creating and saving the module I get this error on Contao 4.4.26.
**Attempted to load class "tl_page" from the global namespace. Did you forget a "use" statement?**

![screenshot 2018-10-27 um 12 32 39](https://user-images.githubusercontent.com/4036452/47602845-71cf9300-d9e4-11e8-8f32-edc9748db9c3.png)

**Comment by bytehead** [comment] 2018-10-27 14:04
Duplicate of #5.

**Closed as completed by bytehead** 2018-10-27 14:04 UTC
Labels: bug, duplicate

**Comment by bytehead** [comment] 2018-10-27 14:47
Please check version 1.1.9, the error should be gone. I could not reproduce your error on my 4.4.26 demo installation.
