### ISSUE TITLE
Events: No navigation links if auto_item is disabled

### ISSUE THREAD

**Issue by xchs** [1up-lab/contao-sibling-navigation#10] opened 2018-10-18 22:08 UTC
**Affected version(s)**

4.6+ (et al.)

**Description**
No navigation links are generated if the option "_Enable auto_item_" is deactivated in the system settings.

**How to reproduce**

To reproduce:
* _System_ > _Settings_ > _Front end configuration_: Disable the _Enable auto_item_ option
* Open a front end (event/news reader) page where the sibling navigation module is included

**Comment by bytehead** [comment] 2018-10-27 14:40
I cannot reproduce this. Tested on Contao 4.6.6 and with sibling-navigation 1.1.8 with the Contao Official Demo.
It works with enabled and disabled `auto_item`.

**Comment by bytehead** [comment] 2018-10-27 14:44
The code which checks the `auto_item` is here:
https://github.com/1up-lab/contao-sibling-navigation/blob/917f8a8fa3448cf4462dc9780b4fefb195b9942e/src/Helper/News/NewsHelper.php#L40-L43

and here:
https://github.com/1up-lab/contao-sibling-navigation/blob/917f8a8fa3448cf4462dc9780b4fefb195b9942e/src/Helper/Event/EventHelper.php#L33-L36

**Comment by xchs** [comment] 2018-10-27 21:03
Hm, I can still reproduce it. I've just repeated the test with version 1.1.9.

To reproduce:
* Set up a new vanilla Contao 4.6.6 installation
* Install the [Contao Official Demo](https://packagist.org/packages/contao/official-demo)
* Require the latest version of the [oneup/contao-sibling-navigation](https://packagist.org/packages/oneup/contao-sibling-navigation) package
* Run the Contao Installtool and update the database
* Log into the Contao back end
* _Content_ > _Articles_: Add a new content element "_Sibling navigation (Events)_" into the "_Event Detail_" article
* Go to the front end page _Contao Official Demo_ > _Modules_ >_Events_ and open the event details of e.g. "_The Contao NRW-Day_" event. The Previous/Next sibling navigation is shown correctly right there.
* Now go to _System_ > _Settings_ and disable the option "_Enable auto_item_" and save the settings
* Again, open the event details page of the "_The Contao NRW-Day_" event. The event sibling navigation is no longer available.

**Comment by bytehead** [comment] 2018-10-28 11:37
I could finally reproduce it, thanks! 
It only happens with `Events`. I have to dig a bit.

**Comment by bytehead** [comment] 2018-10-28 11:48
`1.1.10` is released, should be fixed in there. Thanks for reporting!

**Closed as completed** 2018-10-28 11:47 UTC
Labels: bug

**Comment by xchs** [comment] 2018-10-28 12:25
It now works flawlessly. Thanks a lot.
